pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git url: 'https://github.com/AhmedNabilSharawy/CICD_Jenkins_final_task_iti.git', branch: 'main'
            }
        }
        
        stage('Build Image') {
            steps {
                // Build the image as per your requirements
                sh 'docker build -t app:latest .'
            }
        }
        
        stage('Push to Nexus') {
            steps {
                // Login to the Nexus registry
                withCredentials([usernamePassword(credentialsId: 'nexus', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker login -u $USERNAME -p $PASSWORD 10.103.254.180:5000"
                }
                
                // Tag the image with Nexus registry information
                sh 'docker tag app:latest 10.103.254.180:5000/repository/ahmed-repo/app:latest'
                
                // Push the image to Nexus registry
                sh 'docker push 10.103.254.180:5000/repository/ahmed-repo/app:latest'
            }
        }
        
        stage('Deploy Image') {
            steps {
                // Deploy the app from the Nexus registry to Cluster
                sh """
                kubectl apply -f myapp.yaml 

                kubectl apply -f mysql.yaml 
            }
        }
    }
}
